### PR TITLE
Update tacos.adoc

### PR DESCRIPTION
**Pull request by tetriscode**

### CODE REVIEW

**Comment by joshfix** [comment]
Some of the formatting on this PR seems off to me.  I would recommend conducting a thorough peer review before submitting future PRs.

**Comment by tetriscode** [comment]
@joshfix please bring that up in the sprint retrospective

**Comment by joshfix** [comment]
@tetriscode maybe if there is time.  customer demo is pretty critical.  let's schedule a process meeting for next week.

**Comment by matthewhanson** [comment]
Before accepting any more PRs for this topic I think we need to set up continuous integration.

**Comment by tetriscode** [comment]
@joshfix hit scaling issues on tacos tonight. Went for Blue Moon and a salad

**Comment by joshfix** [comment]
I think this relates to #5

**Pull request merged**
